include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**.mocks.dart'

linter:
  rules:
    no_leading_underscores_for_local_identifiers: false
    library_private_types_in_public_api: false
