// Mocks generated by Mockito 5.2.0 from annotations
// in pluto_grid/test/src/ui/cells/pluto_default_cell_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:ui' as _i5;

import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pluto_grid/pluto_grid.dart' as _i3;
import 'package:rxdart/rxdart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePublishSubject_0<T> extends _i1.Fake
    implements _i2.PublishSubject<T> {}

class _FakePlutoGridColumnSizeConfig_1 extends _i1.Fake
    implements _i3.PlutoGridColumnSizeConfig {}

class _FakeFilteredList_2<E> extends _i1.Fake implements _i3.FilteredList<E> {}

class _FakePlutoGridConfiguration_3 extends _i1.Fake
    implements _i3.PlutoGridConfiguration {}

class _FakePlutoColumnMenuDelegate_4<T> extends _i1.Fake
    implements _i3.PlutoColumnMenuDelegate<T> {}

class _FakePlutoGridLocaleText_5 extends _i1.Fake
    implements _i3.PlutoGridLocaleText {}

class _FakePlutoGridStyleConfig_6 extends _i1.Fake
    implements _i3.PlutoGridStyleConfig {}

class _FakePlutoGridKeyPressed_7 extends _i1.Fake
    implements _i3.PlutoGridKeyPressed {}

class _FakeChangeNotifier_8 extends _i1.Fake implements _i4.ChangeNotifier {}

class _FakeOffset_9 extends _i1.Fake implements _i5.Offset {}

class _FakePlutoAutoSize_10 extends _i1.Fake implements _i3.PlutoAutoSize {}

class _FakePlutoResize_11<T> extends _i1.Fake implements _i3.PlutoResize<T> {}

class _FakePlutoGridCellPosition_12 extends _i1.Fake
    implements _i3.PlutoGridCellPosition {}

class _FakePlutoRow_13 extends _i1.Fake implements _i3.PlutoRow {}

class _FakePlutoGridStateManager_14 extends _i1.Fake
    implements _i3.PlutoGridStateManager {}

class _FakeStreamSubscription_15<T> extends _i1.Fake
    implements _i6.StreamSubscription<T> {}

class _FakeScrollController_16 extends _i1.Fake
    implements _i4.ScrollController {}

class _FakeScrollPosition_17 extends _i1.Fake implements _i4.ScrollPosition {}

/// A class which mocks [PlutoGridStateManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlutoGridStateManager extends _i1.Mock
    implements _i3.PlutoGridStateManager {
  @override
  _i2.PublishSubject<_i3.PlutoNotifierEvent> get streamNotifier =>
      (super.noSuchMethod(Invocation.getter(#streamNotifier),
              returnValue: _FakePublishSubject_0<_i3.PlutoNotifierEvent>())
          as _i2.PublishSubject<_i3.PlutoNotifierEvent>);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  set refColumnGroups(
          _i3.FilteredList<_i3.PlutoColumnGroup>? setColumnGroups) =>
      super.noSuchMethod(Invocation.setter(#refColumnGroups, setColumnGroups),
          returnValueForMissingStub: null);
  @override
  List<_i3.PlutoColumnGroup> get columnGroups =>
      (super.noSuchMethod(Invocation.getter(#columnGroups),
          returnValue: <_i3.PlutoColumnGroup>[]) as List<_i3.PlutoColumnGroup>);
  @override
  bool get hasColumnGroups => (super
          .noSuchMethod(Invocation.getter(#hasColumnGroups), returnValue: false)
      as bool);
  @override
  bool get showColumnGroups =>
      (super.noSuchMethod(Invocation.getter(#showColumnGroups),
          returnValue: false) as bool);
  @override
  _i3.PlutoGridColumnSizeConfig get columnSizeConfig =>
      (super.noSuchMethod(Invocation.getter(#columnSizeConfig),
              returnValue: _FakePlutoGridColumnSizeConfig_1())
          as _i3.PlutoGridColumnSizeConfig);
  @override
  _i3.PlutoAutoSizeMode get columnsAutoSizeMode =>
      (super.noSuchMethod(Invocation.getter(#columnsAutoSizeMode),
          returnValue: _i3.PlutoAutoSizeMode.none) as _i3.PlutoAutoSizeMode);
  @override
  _i3.PlutoResizeMode get columnsResizeMode =>
      (super.noSuchMethod(Invocation.getter(#columnsResizeMode),
          returnValue: _i3.PlutoResizeMode.none) as _i3.PlutoResizeMode);
  @override
  bool get enableColumnsAutoSize =>
      (super.noSuchMethod(Invocation.getter(#enableColumnsAutoSize),
          returnValue: false) as bool);
  @override
  bool get activatedColumnsAutoSize =>
      (super.noSuchMethod(Invocation.getter(#activatedColumnsAutoSize),
          returnValue: false) as bool);
  @override
  _i3.FilteredList<_i3.PlutoColumn> get refColumns =>
      (super.noSuchMethod(Invocation.getter(#refColumns),
              returnValue: _FakeFilteredList_2<_i3.PlutoColumn>())
          as _i3.FilteredList<_i3.PlutoColumn>);
  @override
  set refColumns(_i3.FilteredList<_i3.PlutoColumn>? setColumns) =>
      super.noSuchMethod(Invocation.setter(#refColumns, setColumns),
          returnValueForMissingStub: null);
  @override
  List<_i3.PlutoColumn> get columns =>
      (super.noSuchMethod(Invocation.getter(#columns),
          returnValue: <_i3.PlutoColumn>[]) as List<_i3.PlutoColumn>);
  @override
  List<int> get columnIndexes => (super
          .noSuchMethod(Invocation.getter(#columnIndexes), returnValue: <int>[])
      as List<int>);
  @override
  List<int> get columnIndexesForShowFrozen =>
      (super.noSuchMethod(Invocation.getter(#columnIndexesForShowFrozen),
          returnValue: <int>[]) as List<int>);
  @override
  double get columnsWidth =>
      (super.noSuchMethod(Invocation.getter(#columnsWidth), returnValue: 0.0)
          as double);
  @override
  List<_i3.PlutoColumn> get leftFrozenColumns =>
      (super.noSuchMethod(Invocation.getter(#leftFrozenColumns),
          returnValue: <_i3.PlutoColumn>[]) as List<_i3.PlutoColumn>);
  @override
  List<int> get leftFrozenColumnIndexes =>
      (super.noSuchMethod(Invocation.getter(#leftFrozenColumnIndexes),
          returnValue: <int>[]) as List<int>);
  @override
  double get leftFrozenColumnsWidth =>
      (super.noSuchMethod(Invocation.getter(#leftFrozenColumnsWidth),
          returnValue: 0.0) as double);
  @override
  List<_i3.PlutoColumn> get rightFrozenColumns =>
      (super.noSuchMethod(Invocation.getter(#rightFrozenColumns),
          returnValue: <_i3.PlutoColumn>[]) as List<_i3.PlutoColumn>);
  @override
  List<int> get rightFrozenColumnIndexes =>
      (super.noSuchMethod(Invocation.getter(#rightFrozenColumnIndexes),
          returnValue: <int>[]) as List<int>);
  @override
  double get rightFrozenColumnsWidth =>
      (super.noSuchMethod(Invocation.getter(#rightFrozenColumnsWidth),
          returnValue: 0.0) as double);
  @override
  List<_i3.PlutoColumn> get bodyColumns =>
      (super.noSuchMethod(Invocation.getter(#bodyColumns),
          returnValue: <_i3.PlutoColumn>[]) as List<_i3.PlutoColumn>);
  @override
  List<int> get bodyColumnIndexes =>
      (super.noSuchMethod(Invocation.getter(#bodyColumnIndexes),
          returnValue: <int>[]) as List<int>);
  @override
  double get bodyColumnsWidth => (super
          .noSuchMethod(Invocation.getter(#bodyColumnsWidth), returnValue: 0.0)
      as double);
  @override
  bool get hasSortedColumn => (super
          .noSuchMethod(Invocation.getter(#hasSortedColumn), returnValue: false)
      as bool);
  @override
  List<int> get columnIndexesByShowFrozen =>
      (super.noSuchMethod(Invocation.getter(#columnIndexesByShowFrozen),
          returnValue: <int>[]) as List<int>);
  @override
  bool get isDraggingRow =>
      (super.noSuchMethod(Invocation.getter(#isDraggingRow), returnValue: false)
          as bool);
  @override
  List<_i3.PlutoRow> get dragRows =>
      (super.noSuchMethod(Invocation.getter(#dragRows),
          returnValue: <_i3.PlutoRow>[]) as List<_i3.PlutoRow>);
  @override
  bool get canRowDrag =>
      (super.noSuchMethod(Invocation.getter(#canRowDrag), returnValue: false)
          as bool);
  @override
  set textEditingController(
          _i4.TextEditingController? _textEditingController) =>
      super.noSuchMethod(
          Invocation.setter(#textEditingController, _textEditingController),
          returnValueForMissingStub: null);
  @override
  bool get isEditing =>
      (super.noSuchMethod(Invocation.getter(#isEditing), returnValue: false)
          as bool);
  @override
  bool get autoEditing =>
      (super.noSuchMethod(Invocation.getter(#autoEditing), returnValue: false)
          as bool);
  @override
  List<_i3.PlutoRow> get filterRows =>
      (super.noSuchMethod(Invocation.getter(#filterRows),
          returnValue: <_i3.PlutoRow>[]) as List<_i3.PlutoRow>);
  @override
  bool get hasFilter =>
      (super.noSuchMethod(Invocation.getter(#hasFilter), returnValue: false)
          as bool);
  @override
  bool get keepFocus =>
      (super.noSuchMethod(Invocation.getter(#keepFocus), returnValue: false)
          as bool);
  @override
  bool get hasFocus =>
      (super.noSuchMethod(Invocation.getter(#hasFocus), returnValue: false)
          as bool);
  @override
  _i3.PlutoGridConfiguration get configuration =>
      (super.noSuchMethod(Invocation.getter(#configuration),
              returnValue: _FakePlutoGridConfiguration_3())
          as _i3.PlutoGridConfiguration);
  @override
  _i3.PlutoColumnMenuDelegate<dynamic> get columnMenuDelegate =>
      (super.noSuchMethod(Invocation.getter(#columnMenuDelegate),
              returnValue: _FakePlutoColumnMenuDelegate_4<dynamic>())
          as _i3.PlutoColumnMenuDelegate<dynamic>);
  @override
  _i3.PlutoGridLocaleText get localeText => (super.noSuchMethod(
      Invocation.getter(#localeText),
      returnValue: _FakePlutoGridLocaleText_5()) as _i3.PlutoGridLocaleText);
  @override
  _i3.PlutoGridStyleConfig get style => (super.noSuchMethod(
      Invocation.getter(#style),
      returnValue: _FakePlutoGridStyleConfig_6()) as _i3.PlutoGridStyleConfig);
  @override
  _i3.PlutoGridKeyPressed get keyPressed => (super.noSuchMethod(
      Invocation.getter(#keyPressed),
      returnValue: _FakePlutoGridKeyPressed_7()) as _i3.PlutoGridKeyPressed);
  @override
  _i4.ChangeNotifier get resizingChangeNotifier =>
      (super.noSuchMethod(Invocation.getter(#resizingChangeNotifier),
          returnValue: _FakeChangeNotifier_8()) as _i4.ChangeNotifier);
  @override
  double get headerHeight =>
      (super.noSuchMethod(Invocation.getter(#headerHeight), returnValue: 0.0)
          as double);
  @override
  double get footerHeight =>
      (super.noSuchMethod(Invocation.getter(#footerHeight), returnValue: 0.0)
          as double);
  @override
  double get columnRowContainerHeight =>
      (super.noSuchMethod(Invocation.getter(#columnRowContainerHeight),
          returnValue: 0.0) as double);
  @override
  double get rowContainerHeight =>
      (super.noSuchMethod(Invocation.getter(#rowContainerHeight),
          returnValue: 0.0) as double);
  @override
  bool get showFrozenColumn =>
      (super.noSuchMethod(Invocation.getter(#showFrozenColumn),
          returnValue: false) as bool);
  @override
  bool get showColumnTitle => (super
          .noSuchMethod(Invocation.getter(#showColumnTitle), returnValue: false)
      as bool);
  @override
  bool get showColumnFooter =>
      (super.noSuchMethod(Invocation.getter(#showColumnFooter),
          returnValue: false) as bool);
  @override
  bool get showColumnFilter =>
      (super.noSuchMethod(Invocation.getter(#showColumnFilter),
          returnValue: false) as bool);
  @override
  bool get showHeader =>
      (super.noSuchMethod(Invocation.getter(#showHeader), returnValue: false)
          as bool);
  @override
  bool get showFooter =>
      (super.noSuchMethod(Invocation.getter(#showFooter), returnValue: false)
          as bool);
  @override
  bool get showLoading =>
      (super.noSuchMethod(Invocation.getter(#showLoading), returnValue: false)
          as bool);
  @override
  bool get hasLeftFrozenColumns =>
      (super.noSuchMethod(Invocation.getter(#hasLeftFrozenColumns),
          returnValue: false) as bool);
  @override
  bool get hasRightFrozenColumns =>
      (super.noSuchMethod(Invocation.getter(#hasRightFrozenColumns),
          returnValue: false) as bool);
  @override
  double get headerBottomOffset =>
      (super.noSuchMethod(Invocation.getter(#headerBottomOffset),
          returnValue: 0.0) as double);
  @override
  double get footerTopOffset =>
      (super.noSuchMethod(Invocation.getter(#footerTopOffset), returnValue: 0.0)
          as double);
  @override
  double get columnHeight =>
      (super.noSuchMethod(Invocation.getter(#columnHeight), returnValue: 0.0)
          as double);
  @override
  double get columnFooterHeight =>
      (super.noSuchMethod(Invocation.getter(#columnFooterHeight),
          returnValue: 0.0) as double);
  @override
  double get columnGroupHeight => (super
          .noSuchMethod(Invocation.getter(#columnGroupHeight), returnValue: 0.0)
      as double);
  @override
  double get columnFilterHeight =>
      (super.noSuchMethod(Invocation.getter(#columnFilterHeight),
          returnValue: 0.0) as double);
  @override
  double get columnBottomOffset =>
      (super.noSuchMethod(Invocation.getter(#columnBottomOffset),
          returnValue: 0.0) as double);
  @override
  double get rowsTopOffset =>
      (super.noSuchMethod(Invocation.getter(#rowsTopOffset), returnValue: 0.0)
          as double);
  @override
  double get rowHeight =>
      (super.noSuchMethod(Invocation.getter(#rowHeight), returnValue: 0.0)
          as double);
  @override
  double get rowTotalHeight =>
      (super.noSuchMethod(Invocation.getter(#rowTotalHeight), returnValue: 0.0)
          as double);
  @override
  double get bodyTopOffset =>
      (super.noSuchMethod(Invocation.getter(#bodyTopOffset), returnValue: 0.0)
          as double);
  @override
  double get bodyLeftOffset =>
      (super.noSuchMethod(Invocation.getter(#bodyLeftOffset), returnValue: 0.0)
          as double);
  @override
  double get bodyRightOffset =>
      (super.noSuchMethod(Invocation.getter(#bodyRightOffset), returnValue: 0.0)
          as double);
  @override
  double get bodyLeftScrollOffset =>
      (super.noSuchMethod(Invocation.getter(#bodyLeftScrollOffset),
          returnValue: 0.0) as double);
  @override
  double get bodyRightScrollOffset =>
      (super.noSuchMethod(Invocation.getter(#bodyRightScrollOffset),
          returnValue: 0.0) as double);
  @override
  double get bodyUpScrollOffset =>
      (super.noSuchMethod(Invocation.getter(#bodyUpScrollOffset),
          returnValue: 0.0) as double);
  @override
  double get bodyDownScrollOffset =>
      (super.noSuchMethod(Invocation.getter(#bodyDownScrollOffset),
          returnValue: 0.0) as double);
  @override
  double get leftFrozenRightOffset =>
      (super.noSuchMethod(Invocation.getter(#leftFrozenRightOffset),
          returnValue: 0.0) as double);
  @override
  double get rightFrozenLeftOffset =>
      (super.noSuchMethod(Invocation.getter(#rightFrozenLeftOffset),
          returnValue: 0.0) as double);
  @override
  double get rightBlankOffset => (super
          .noSuchMethod(Invocation.getter(#rightBlankOffset), returnValue: 0.0)
      as double);
  @override
  double get scrollOffsetByFrozenColumn =>
      (super.noSuchMethod(Invocation.getter(#scrollOffsetByFrozenColumn),
          returnValue: 0.0) as double);
  @override
  _i5.TextDirection get textDirection =>
      (super.noSuchMethod(Invocation.getter(#textDirection),
          returnValue: _i5.TextDirection.rtl) as _i5.TextDirection);
  @override
  bool get isLTR =>
      (super.noSuchMethod(Invocation.getter(#isLTR), returnValue: false)
          as bool);
  @override
  bool get isRTL =>
      (super.noSuchMethod(Invocation.getter(#isRTL), returnValue: false)
          as bool);
  @override
  int get page =>
      (super.noSuchMethod(Invocation.getter(#page), returnValue: 0) as int);
  @override
  int get pageSize =>
      (super.noSuchMethod(Invocation.getter(#pageSize), returnValue: 0) as int);
  @override
  int get totalPage =>
      (super.noSuchMethod(Invocation.getter(#totalPage), returnValue: 0)
          as int);
  @override
  bool get isPaginated =>
      (super.noSuchMethod(Invocation.getter(#isPaginated), returnValue: false)
          as bool);
  @override
  _i3.FilteredList<_i3.PlutoRow> get refRows =>
      (super.noSuchMethod(Invocation.getter(#refRows),
              returnValue: _FakeFilteredList_2<_i3.PlutoRow>())
          as _i3.FilteredList<_i3.PlutoRow>);
  @override
  set refRows(_i3.FilteredList<_i3.PlutoRow>? setRows) =>
      super.noSuchMethod(Invocation.setter(#refRows, setRows),
          returnValueForMissingStub: null);
  @override
  List<_i3.PlutoRow> get rows => (super.noSuchMethod(Invocation.getter(#rows),
      returnValue: <_i3.PlutoRow>[]) as List<_i3.PlutoRow>);
  @override
  List<_i3.PlutoRow> get checkedRows =>
      (super.noSuchMethod(Invocation.getter(#checkedRows),
          returnValue: <_i3.PlutoRow>[]) as List<_i3.PlutoRow>);
  @override
  List<_i3.PlutoRow> get unCheckedRows =>
      (super.noSuchMethod(Invocation.getter(#unCheckedRows),
          returnValue: <_i3.PlutoRow>[]) as List<_i3.PlutoRow>);
  @override
  bool get hasCheckedRow =>
      (super.noSuchMethod(Invocation.getter(#hasCheckedRow), returnValue: false)
          as bool);
  @override
  bool get hasUnCheckedRow => (super
          .noSuchMethod(Invocation.getter(#hasUnCheckedRow), returnValue: false)
      as bool);
  @override
  bool get isHorizontalOverScrolled =>
      (super.noSuchMethod(Invocation.getter(#isHorizontalOverScrolled),
          returnValue: false) as bool);
  @override
  double get correctHorizontalOffset =>
      (super.noSuchMethod(Invocation.getter(#correctHorizontalOffset),
          returnValue: 0.0) as double);
  @override
  _i5.Offset get directionalScrollEdgeOffset =>
      (super.noSuchMethod(Invocation.getter(#directionalScrollEdgeOffset),
          returnValue: _FakeOffset_9()) as _i5.Offset);
  @override
  bool get isSelecting =>
      (super.noSuchMethod(Invocation.getter(#isSelecting), returnValue: false)
          as bool);
  @override
  _i3.PlutoGridSelectingMode get selectingMode =>
      (super.noSuchMethod(Invocation.getter(#selectingMode),
              returnValue: _i3.PlutoGridSelectingMode.cell)
          as _i3.PlutoGridSelectingMode);
  @override
  List<_i3.PlutoGridSelectingCellPosition> get currentSelectingPositionList =>
      (super.noSuchMethod(Invocation.getter(#currentSelectingPositionList),
              returnValue: <_i3.PlutoGridSelectingCellPosition>[])
          as List<_i3.PlutoGridSelectingCellPosition>);
  @override
  bool get hasCurrentSelectingPosition =>
      (super.noSuchMethod(Invocation.getter(#hasCurrentSelectingPosition),
          returnValue: false) as bool);
  @override
  List<_i3.PlutoRow> get currentSelectingRows =>
      (super.noSuchMethod(Invocation.getter(#currentSelectingRows),
          returnValue: <_i3.PlutoRow>[]) as List<_i3.PlutoRow>);
  @override
  String get currentSelectingText =>
      (super.noSuchMethod(Invocation.getter(#currentSelectingText),
          returnValue: '') as String);
  @override
  set headerHeight(double? value) =>
      super.noSuchMethod(Invocation.setter(#headerHeight, value),
          returnValueForMissingStub: null);
  @override
  set footerHeight(double? value) =>
      super.noSuchMethod(Invocation.setter(#footerHeight, value),
          returnValueForMissingStub: null);
  @override
  set columnFooterHeight(double? value) =>
      super.noSuchMethod(Invocation.setter(#columnFooterHeight, value),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
  @override
  void notifyListenersOnPostFrame() =>
      super.noSuchMethod(Invocation.method(#notifyListenersOnPostFrame, []),
          returnValueForMissingStub: null);
  @override
  void addListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void setCurrentCellPosition(_i3.PlutoGridCellPosition? cellPosition,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(
              #setCurrentCellPosition, [cellPosition], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void updateCurrentCellPosition({bool? notify = true}) => super.noSuchMethod(
      Invocation.method(#updateCurrentCellPosition, [], {#notify: notify}),
      returnValueForMissingStub: null);
  @override
  int? columnIdxByCellKeyAndRowIdx(_i4.Key? cellKey, int? rowIdx) =>
      (super.noSuchMethod(Invocation.method(
          #columnIdxByCellKeyAndRowIdx, [cellKey, rowIdx])) as int?);
  @override
  void clearCurrentCell({bool? notify = true}) => super.noSuchMethod(
      Invocation.method(#clearCurrentCell, [], {#notify: notify}),
      returnValueForMissingStub: null);
  @override
  void setCurrentCell(_i3.PlutoCell? cell, int? rowIdx,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#setCurrentCell, [cell, rowIdx], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  bool canMoveCell(_i3.PlutoGridCellPosition? cellPosition,
          _i3.PlutoMoveDirection? direction) =>
      (super.noSuchMethod(
          Invocation.method(#canMoveCell, [cellPosition, direction]),
          returnValue: false) as bool);
  @override
  bool canNotMoveCell(_i3.PlutoGridCellPosition? cellPosition,
          _i3.PlutoMoveDirection? direction) =>
      (super.noSuchMethod(
          Invocation.method(#canNotMoveCell, [cellPosition, direction]),
          returnValue: false) as bool);
  @override
  bool canChangeCellValue(
          {_i3.PlutoColumn? column,
          _i3.PlutoRow? row,
          dynamic newValue,
          dynamic oldValue}) =>
      (super.noSuchMethod(
          Invocation.method(#canChangeCellValue, [], {
            #column: column,
            #row: row,
            #newValue: newValue,
            #oldValue: oldValue
          }),
          returnValue: false) as bool);
  @override
  bool canNotChangeCellValue(
          {_i3.PlutoColumn? column,
          _i3.PlutoRow? row,
          dynamic newValue,
          dynamic oldValue}) =>
      (super.noSuchMethod(
          Invocation.method(#canNotChangeCellValue, [], {
            #column: column,
            #row: row,
            #newValue: newValue,
            #oldValue: oldValue
          }),
          returnValue: false) as bool);
  @override
  dynamic filteredCellValue(
          {_i3.PlutoColumn? column, dynamic newValue, dynamic oldValue}) =>
      super.noSuchMethod(Invocation.method(#filteredCellValue, [],
          {#column: column, #newValue: newValue, #oldValue: oldValue}));
  @override
  bool isCurrentCell(_i3.PlutoCell? cell) =>
      (super.noSuchMethod(Invocation.method(#isCurrentCell, [cell]),
          returnValue: false) as bool);
  @override
  bool isInvalidCellPosition(_i3.PlutoGridCellPosition? cellPosition) => (super
      .noSuchMethod(Invocation.method(#isInvalidCellPosition, [cellPosition]),
          returnValue: false) as bool);
  @override
  void setShowColumnGroups(bool? flag, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#setShowColumnGroups, [flag], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  List<_i3.PlutoColumnGroupPair> separateLinkedGroup(
          {List<_i3.PlutoColumnGroup>? columnGroupList,
          List<_i3.PlutoColumn>? columns}) =>
      (super.noSuchMethod(
              Invocation.method(#separateLinkedGroup, [],
                  {#columnGroupList: columnGroupList, #columns: columns}),
              returnValue: <_i3.PlutoColumnGroupPair>[])
          as List<_i3.PlutoColumnGroupPair>);
  @override
  int columnGroupDepth(List<_i3.PlutoColumnGroup>? columnGroupList) => (super
      .noSuchMethod(Invocation.method(#columnGroupDepth, [columnGroupList]),
          returnValue: 0) as int);
  @override
  void removeColumnsInColumnGroup(List<_i3.PlutoColumn>? columns,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(
              #removeColumnsInColumnGroup, [columns], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void activateColumnsAutoSize() =>
      super.noSuchMethod(Invocation.method(#activateColumnsAutoSize, []),
          returnValueForMissingStub: null);
  @override
  void deactivateColumnsAutoSize() =>
      super.noSuchMethod(Invocation.method(#deactivateColumnsAutoSize, []),
          returnValueForMissingStub: null);
  @override
  _i3.PlutoAutoSize getColumnsAutoSizeHelper(
          {Iterable<_i3.PlutoColumn>? columns, double? maxWidth}) =>
      (super.noSuchMethod(
          Invocation.method(#getColumnsAutoSizeHelper, [],
              {#columns: columns, #maxWidth: maxWidth}),
          returnValue: _FakePlutoAutoSize_10()) as _i3.PlutoAutoSize);
  @override
  _i3.PlutoResize<dynamic> getColumnsResizeHelper(
          {List<_i3.PlutoColumn>? columns,
          _i3.PlutoColumn? column,
          double? offset}) =>
      (super.noSuchMethod(
              Invocation.method(#getColumnsResizeHelper, [],
                  {#columns: columns, #column: column, #offset: offset}),
              returnValue: _FakePlutoResize_11<dynamic>())
          as _i3.PlutoResize<dynamic>);
  @override
  void setColumnSizeConfig(_i3.PlutoGridColumnSizeConfig? config) =>
      super.noSuchMethod(Invocation.method(#setColumnSizeConfig, [config]),
          returnValueForMissingStub: null);
  @override
  void toggleFrozenColumn(
          _i3.PlutoColumn? column, _i3.PlutoColumnFrozen? frozen) =>
      super.noSuchMethod(
          Invocation.method(#toggleFrozenColumn, [column, frozen]),
          returnValueForMissingStub: null);
  @override
  void toggleSortColumn(_i3.PlutoColumn? column) =>
      super.noSuchMethod(Invocation.method(#toggleSortColumn, [column]),
          returnValueForMissingStub: null);
  @override
  int? columnIndex(_i3.PlutoColumn? column) =>
      (super.noSuchMethod(Invocation.method(#columnIndex, [column])) as int?);
  @override
  void insertColumns(int? columnIdx, List<_i3.PlutoColumn>? columns) => super
      .noSuchMethod(Invocation.method(#insertColumns, [columnIdx, columns]),
          returnValueForMissingStub: null);
  @override
  void removeColumns(List<_i3.PlutoColumn>? columns) =>
      super.noSuchMethod(Invocation.method(#removeColumns, [columns]),
          returnValueForMissingStub: null);
  @override
  void moveColumn({_i3.PlutoColumn? column, _i3.PlutoColumn? targetColumn}) =>
      super.noSuchMethod(
          Invocation.method(
              #moveColumn, [], {#column: column, #targetColumn: targetColumn}),
          returnValueForMissingStub: null);
  @override
  void resizeColumn(_i3.PlutoColumn? column, double? offset) =>
      super.noSuchMethod(Invocation.method(#resizeColumn, [column, offset]),
          returnValueForMissingStub: null);
  @override
  void autoFitColumn(_i4.BuildContext? context, _i3.PlutoColumn? column) =>
      super.noSuchMethod(Invocation.method(#autoFitColumn, [context, column]),
          returnValueForMissingStub: null);
  @override
  void hideColumn(_i3.PlutoColumn? column, bool? hide, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#hideColumn, [column, hide], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void hideColumns(List<_i3.PlutoColumn>? columns, bool? hide,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#hideColumns, [columns, hide], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void sortAscending(_i3.PlutoColumn? column, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#sortAscending, [column], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void sortDescending(_i3.PlutoColumn? column, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#sortDescending, [column], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void sortBySortIdx(_i3.PlutoColumn? column, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#sortBySortIdx, [column], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void showSetColumnsPopup(_i4.BuildContext? context) =>
      super.noSuchMethod(Invocation.method(#showSetColumnsPopup, [context]),
          returnValueForMissingStub: null);
  @override
  bool limitResizeColumn(_i3.PlutoColumn? column, double? offset) => (super
      .noSuchMethod(Invocation.method(#limitResizeColumn, [column, offset]),
          returnValue: false) as bool);
  @override
  bool limitMoveColumn(
          {_i3.PlutoColumn? column, _i3.PlutoColumn? targetColumn}) =>
      (super.noSuchMethod(
          Invocation.method(#limitMoveColumn, [],
              {#column: column, #targetColumn: targetColumn}),
          returnValue: false) as bool);
  @override
  bool limitToggleFrozenColumn(
          _i3.PlutoColumn? column, _i3.PlutoColumnFrozen? frozen) =>
      (super.noSuchMethod(
          Invocation.method(#limitToggleFrozenColumn, [column, frozen]),
          returnValue: false) as bool);
  @override
  bool limitHideColumn(_i3.PlutoColumn? column, bool? hide,
          {double? accumulateWidth = 0.0}) =>
      (super.noSuchMethod(
          Invocation.method(#limitHideColumn, [column, hide],
              {#accumulateWidth: accumulateWidth}),
          returnValue: false) as bool);
  @override
  void setIsDraggingRow(bool? flag, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#setIsDraggingRow, [flag], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void setDragRows(List<_i3.PlutoRow>? rows, {bool? notify = true}) => super
      .noSuchMethod(Invocation.method(#setDragRows, [rows], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void setDragTargetRowIdx(int? rowIdx, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#setDragTargetRowIdx, [rowIdx], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  bool isRowIdxDragTarget(int? rowIdx) =>
      (super.noSuchMethod(Invocation.method(#isRowIdxDragTarget, [rowIdx]),
          returnValue: false) as bool);
  @override
  bool isRowIdxTopDragTarget(int? rowIdx) =>
      (super.noSuchMethod(Invocation.method(#isRowIdxTopDragTarget, [rowIdx]),
          returnValue: false) as bool);
  @override
  bool isRowIdxBottomDragTarget(int? rowIdx) => (super.noSuchMethod(
      Invocation.method(#isRowIdxBottomDragTarget, [rowIdx]),
      returnValue: false) as bool);
  @override
  bool isRowBeingDragged(_i4.Key? rowKey) =>
      (super.noSuchMethod(Invocation.method(#isRowBeingDragged, [rowKey]),
          returnValue: false) as bool);
  @override
  void setEditing(bool? flag, {bool? notify = true}) => super.noSuchMethod(
      Invocation.method(#setEditing, [flag], {#notify: notify}),
      returnValueForMissingStub: null);
  @override
  void setAutoEditing(bool? flag, {bool? notify = true}) => super.noSuchMethod(
      Invocation.method(#setAutoEditing, [flag], {#notify: notify}),
      returnValueForMissingStub: null);
  @override
  void toggleEditing({bool? notify = true}) => super.noSuchMethod(
      Invocation.method(#toggleEditing, [], {#notify: notify}),
      returnValueForMissingStub: null);
  @override
  void pasteCellValue(List<List<String>>? textList) =>
      super.noSuchMethod(Invocation.method(#pasteCellValue, [textList]),
          returnValueForMissingStub: null);
  @override
  dynamic castValueByColumnType(dynamic value, _i3.PlutoColumn? column) => super
      .noSuchMethod(Invocation.method(#castValueByColumnType, [value, column]));
  @override
  void changeCellValue(_i3.PlutoCell? cell, dynamic value,
          {bool? callOnChangedEvent = true,
          bool? force = false,
          bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#changeCellValue, [
            cell,
            value
          ], {
            #callOnChangedEvent: callOnChangedEvent,
            #force: force,
            #notify: notify
          }),
          returnValueForMissingStub: null);
  @override
  void setFilter(_i3.FilteredListFilter<_i3.PlutoRow>? filter,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#setFilter, [filter], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void setFilterWithFilterRows(List<_i3.PlutoRow>? rows,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(
              #setFilterWithFilterRows, [rows], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void setFilterRows(List<_i3.PlutoRow>? rows) =>
      super.noSuchMethod(Invocation.method(#setFilterRows, [rows]),
          returnValueForMissingStub: null);
  @override
  List<_i3.PlutoRow> filterRowsByField(String? columnField) =>
      (super.noSuchMethod(Invocation.method(#filterRowsByField, [columnField]),
          returnValue: <_i3.PlutoRow>[]) as List<_i3.PlutoRow>);
  @override
  bool isFilteredColumn(_i3.PlutoColumn? column) =>
      (super.noSuchMethod(Invocation.method(#isFilteredColumn, [column]),
          returnValue: false) as bool);
  @override
  void removeColumnsInFilterRows(List<_i3.PlutoColumn>? columns,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(
              #removeColumnsInFilterRows, [columns], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void showFilterPopup(_i4.BuildContext? context,
          {_i3.PlutoColumn? calledColumn}) =>
      super.noSuchMethod(
          Invocation.method(
              #showFilterPopup, [context], {#calledColumn: calledColumn}),
          returnValueForMissingStub: null);
  @override
  void setGridFocusNode(_i4.FocusNode? focusNode) =>
      super.noSuchMethod(Invocation.method(#setGridFocusNode, [focusNode]),
          returnValueForMissingStub: null);
  @override
  void setKeepFocus(bool? flag, {bool? notify = true}) => super.noSuchMethod(
      Invocation.method(#setKeepFocus, [flag], {#notify: notify}),
      returnValueForMissingStub: null);
  @override
  void nextFocusOfColumnFilter(_i3.PlutoColumn? column,
          {bool? reversed = false}) =>
      super.noSuchMethod(
          Invocation.method(
              #nextFocusOfColumnFilter, [column], {#reversed: reversed}),
          returnValueForMissingStub: null);
  @override
  void setGridKey(_i4.GlobalKey<_i4.State<_i4.StatefulWidget>>? key) =>
      super.noSuchMethod(Invocation.method(#setGridKey, [key]),
          returnValueForMissingStub: null);
  @override
  void setKeyManager(_i3.PlutoGridKeyManager? keyManager) =>
      super.noSuchMethod(Invocation.method(#setKeyManager, [keyManager]),
          returnValueForMissingStub: null);
  @override
  void setEventManager(_i3.PlutoGridEventManager? eventManager) =>
      super.noSuchMethod(Invocation.method(#setEventManager, [eventManager]),
          returnValueForMissingStub: null);
  @override
  void setGridMode(_i3.PlutoGridMode? mode) =>
      super.noSuchMethod(Invocation.method(#setGridMode, [mode]),
          returnValueForMissingStub: null);
  @override
  void setOnChanged(_i3.PlutoOnChangedEventCallback? onChanged) =>
      super.noSuchMethod(Invocation.method(#setOnChanged, [onChanged]),
          returnValueForMissingStub: null);
  @override
  void setColumnMenuDelegate(
          _i3.PlutoColumnMenuDelegate<dynamic>? columnMenuDelegate) =>
      super.noSuchMethod(
          Invocation.method(#setColumnMenuDelegate, [columnMenuDelegate]),
          returnValueForMissingStub: null);
  @override
  void setCreateHeader(_i3.CreateHeaderCallBack? createHeader) =>
      super.noSuchMethod(Invocation.method(#setCreateHeader, [createHeader]),
          returnValueForMissingStub: null);
  @override
  void setCreateFooter(_i3.CreateFooterCallBack? createFooter) =>
      super.noSuchMethod(Invocation.method(#setCreateFooter, [createFooter]),
          returnValueForMissingStub: null);
  @override
  void setOnSelected(_i3.PlutoOnSelectedEventCallback? onSelected) =>
      super.noSuchMethod(Invocation.method(#setOnSelected, [onSelected]),
          returnValueForMissingStub: null);
  @override
  void setOnSorted(_i3.PlutoOnSortedEventCallback? onSorted) =>
      super.noSuchMethod(Invocation.method(#setOnSorted, [onSorted]),
          returnValueForMissingStub: null);
  @override
  void setOnRowChecked(_i3.PlutoOnRowCheckedEventCallback? onRowChecked) =>
      super.noSuchMethod(Invocation.method(#setOnRowChecked, [onRowChecked]),
          returnValueForMissingStub: null);
  @override
  void setOnRowDoubleTap(
          _i3.PlutoOnRowDoubleTapEventCallback? onRowDoubleTap) =>
      super.noSuchMethod(
          Invocation.method(#setOnRowDoubleTap, [onRowDoubleTap]),
          returnValueForMissingStub: null);
  @override
  void setOnRowSecondaryTap(
          _i3.PlutoOnRowSecondaryTapEventCallback? onRowSecondaryTap) =>
      super.noSuchMethod(
          Invocation.method(#setOnRowSecondaryTap, [onRowSecondaryTap]),
          returnValueForMissingStub: null);
  @override
  void setOnRowsMoved(_i3.PlutoOnRowsMovedEventCallback? onRowsMoved) =>
      super.noSuchMethod(Invocation.method(#setOnRowsMoved, [onRowsMoved]),
          returnValueForMissingStub: null);
  @override
  void setConfiguration(_i3.PlutoGridConfiguration? configuration,
          {bool? updateLocale = true, bool? applyColumnFilter = true}) =>
      super.noSuchMethod(
          Invocation.method(#setConfiguration, [
            configuration
          ], {
            #updateLocale: updateLocale,
            #applyColumnFilter: applyColumnFilter
          }),
          returnValueForMissingStub: null);
  @override
  void resetCurrentState({bool? notify = true}) => super.noSuchMethod(
      Invocation.method(#resetCurrentState, [], {#notify: notify}),
      returnValueForMissingStub: null);
  @override
  void handleOnSelected() =>
      super.noSuchMethod(Invocation.method(#handleOnSelected, []),
          returnValueForMissingStub: null);
  @override
  void forceUpdate() => super.noSuchMethod(Invocation.method(#forceUpdate, []),
      returnValueForMissingStub: null);
  @override
  _i3.PlutoGridCellPosition cellPositionToMove(
          _i3.PlutoGridCellPosition? cellPosition,
          _i3.PlutoMoveDirection? direction) =>
      (super.noSuchMethod(
              Invocation.method(#cellPositionToMove, [cellPosition, direction]),
              returnValue: _FakePlutoGridCellPosition_12())
          as _i3.PlutoGridCellPosition);
  @override
  void moveCurrentCell(_i3.PlutoMoveDirection? direction,
          {bool? force = false, bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(
              #moveCurrentCell, [direction], {#force: force, #notify: notify}),
          returnValueForMissingStub: null);
  @override
  void moveCurrentCellToEdgeOfColumns(_i3.PlutoMoveDirection? direction,
          {bool? force = false, bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#moveCurrentCellToEdgeOfColumns, [direction],
              {#force: force, #notify: notify}),
          returnValueForMissingStub: null);
  @override
  void moveCurrentCellToEdgeOfRows(_i3.PlutoMoveDirection? direction,
          {bool? force = false, bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#moveCurrentCellToEdgeOfRows, [direction],
              {#force: force, #notify: notify}),
          returnValueForMissingStub: null);
  @override
  void moveCurrentCellByRowIdx(int? rowIdx, _i3.PlutoMoveDirection? direction,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(
              #moveCurrentCellByRowIdx, [rowIdx, direction], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void moveSelectingCell(_i3.PlutoMoveDirection? direction) =>
      super.noSuchMethod(Invocation.method(#moveSelectingCell, [direction]),
          returnValueForMissingStub: null);
  @override
  void moveSelectingCellToEdgeOfColumns(_i3.PlutoMoveDirection? direction,
          {bool? force = false, bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#moveSelectingCellToEdgeOfColumns, [direction],
              {#force: force, #notify: notify}),
          returnValueForMissingStub: null);
  @override
  void moveSelectingCellToEdgeOfRows(_i3.PlutoMoveDirection? direction,
          {bool? force = false, bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#moveSelectingCellToEdgeOfRows, [direction],
              {#force: force, #notify: notify}),
          returnValueForMissingStub: null);
  @override
  void moveSelectingCellByRowIdx(int? rowIdx, _i3.PlutoMoveDirection? direction,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#moveSelectingCellByRowIdx, [rowIdx, direction],
              {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void setLayout(_i4.BoxConstraints? size) =>
      super.noSuchMethod(Invocation.method(#setLayout, [size]),
          returnValueForMissingStub: null);
  @override
  void setShowColumnTitle(bool? flag, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#setShowColumnTitle, [flag], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void setShowColumnFooter(bool? flag, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#setShowColumnFooter, [flag], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void setShowColumnFilter(bool? flag, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#setShowColumnFilter, [flag], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void setShowLoading(bool? flag, {bool? notify = true}) => super.noSuchMethod(
      Invocation.method(#setShowLoading, [flag], {#notify: notify}),
      returnValueForMissingStub: null);
  @override
  void resetShowFrozenColumn() =>
      super.noSuchMethod(Invocation.method(#resetShowFrozenColumn, []),
          returnValueForMissingStub: null);
  @override
  bool shouldShowFrozenColumns(double? width) =>
      (super.noSuchMethod(Invocation.method(#shouldShowFrozenColumns, [width]),
          returnValue: false) as bool);
  @override
  bool enoughFrozenColumnsWidth(double? width) =>
      (super.noSuchMethod(Invocation.method(#enoughFrozenColumnsWidth, [width]),
          returnValue: false) as bool);
  @override
  void notifyResizingListeners() =>
      super.noSuchMethod(Invocation.method(#notifyResizingListeners, []),
          returnValueForMissingStub: null);
  @override
  void setTextDirection(_i5.TextDirection? textDirection) =>
      super.noSuchMethod(Invocation.method(#setTextDirection, [textDirection]),
          returnValueForMissingStub: null);
  @override
  void setGridGlobalOffset(_i5.Offset? offset) =>
      super.noSuchMethod(Invocation.method(#setGridGlobalOffset, [offset]),
          returnValueForMissingStub: null);
  @override
  void setPageSize(int? pageSize, {bool? notify = true}) => super.noSuchMethod(
      Invocation.method(#setPageSize, [pageSize], {#notify: notify}),
      returnValueForMissingStub: null);
  @override
  void setPage(int? page, {bool? notify = true}) =>
      super.noSuchMethod(Invocation.method(#setPage, [page], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void resetPage({bool? notify = true}) =>
      super.noSuchMethod(Invocation.method(#resetPage, [], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  int? getRowIdxByOffset(double? offset) =>
      (super.noSuchMethod(Invocation.method(#getRowIdxByOffset, [offset]))
          as int?);
  @override
  _i3.PlutoRow getNewRow() =>
      (super.noSuchMethod(Invocation.method(#getNewRow, []),
          returnValue: _FakePlutoRow_13()) as _i3.PlutoRow);
  @override
  List<_i3.PlutoRow> getNewRows({int? count = 1}) =>
      (super.noSuchMethod(Invocation.method(#getNewRows, [], {#count: count}),
          returnValue: <_i3.PlutoRow>[]) as List<_i3.PlutoRow>);
  @override
  List<_i3.PlutoRow> setSortIdxOfRows(List<_i3.PlutoRow>? rows,
          {bool? increase = true, int? start = 0}) =>
      (super.noSuchMethod(
          Invocation.method(
              #setSortIdxOfRows, [rows], {#increase: increase, #start: start}),
          returnValue: <_i3.PlutoRow>[]) as List<_i3.PlutoRow>);
  @override
  void setRowChecked(_i3.PlutoRow? row, bool? flag, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#setRowChecked, [row, flag], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void insertRows(int? rowIdx, List<_i3.PlutoRow>? rows,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#insertRows, [rowIdx, rows], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void prependNewRows({int? count = 1}) => super.noSuchMethod(
      Invocation.method(#prependNewRows, [], {#count: count}),
      returnValueForMissingStub: null);
  @override
  void prependRows(List<_i3.PlutoRow>? rows) =>
      super.noSuchMethod(Invocation.method(#prependRows, [rows]),
          returnValueForMissingStub: null);
  @override
  void appendNewRows({int? count = 1}) =>
      super.noSuchMethod(Invocation.method(#appendNewRows, [], {#count: count}),
          returnValueForMissingStub: null);
  @override
  void appendRows(List<_i3.PlutoRow>? rows) =>
      super.noSuchMethod(Invocation.method(#appendRows, [rows]),
          returnValueForMissingStub: null);
  @override
  void removeCurrentRow() =>
      super.noSuchMethod(Invocation.method(#removeCurrentRow, []),
          returnValueForMissingStub: null);
  @override
  void removeRows(List<_i3.PlutoRow>? rows, {bool? notify = true}) => super
      .noSuchMethod(Invocation.method(#removeRows, [rows], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void removeAllRows({bool? notify = true}) => super.noSuchMethod(
      Invocation.method(#removeAllRows, [], {#notify: notify}),
      returnValueForMissingStub: null);
  @override
  void moveRowsByOffset(List<_i3.PlutoRow>? rows, double? offset,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(
              #moveRowsByOffset, [rows, offset], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void moveRowsByIndex(List<_i3.PlutoRow>? rows, int? indexToMove,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(
              #moveRowsByIndex, [rows, indexToMove], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void toggleAllRowChecked(bool? flag, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#toggleAllRowChecked, [flag], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void setRowColorCallback(_i3.PlutoRowColorCallback? rowColorCallback) => super
      .noSuchMethod(Invocation.method(#setRowColorCallback, [rowColorCallback]),
          returnValueForMissingStub: null);
  @override
  void setScroll(_i3.PlutoGridScrollController? scroll) =>
      super.noSuchMethod(Invocation.method(#setScroll, [scroll]),
          returnValueForMissingStub: null);
  @override
  _i5.Offset toDirectionalOffset(_i5.Offset? offset) =>
      (super.noSuchMethod(Invocation.method(#toDirectionalOffset, [offset]),
          returnValue: _FakeOffset_9()) as _i5.Offset);
  @override
  void scrollByDirection(_i3.PlutoMoveDirection? direction, double? offset) =>
      super.noSuchMethod(
          Invocation.method(#scrollByDirection, [direction, offset]),
          returnValueForMissingStub: null);
  @override
  bool canHorizontalCellScrollByDirection(
          _i3.PlutoMoveDirection? direction, _i3.PlutoColumn? columnToMove) =>
      (super.noSuchMethod(
          Invocation.method(
              #canHorizontalCellScrollByDirection, [direction, columnToMove]),
          returnValue: false) as bool);
  @override
  void moveScrollByRow(_i3.PlutoMoveDirection? direction, int? rowIdx) => super
      .noSuchMethod(Invocation.method(#moveScrollByRow, [direction, rowIdx]),
          returnValueForMissingStub: null);
  @override
  void moveScrollByColumn(_i3.PlutoMoveDirection? direction, int? columnIdx) =>
      super.noSuchMethod(
          Invocation.method(#moveScrollByColumn, [direction, columnIdx]),
          returnValueForMissingStub: null);
  @override
  bool needMovingScroll(_i5.Offset? offset, _i3.PlutoMoveDirection? move) =>
      (super.noSuchMethod(Invocation.method(#needMovingScroll, [offset, move]),
          returnValue: false) as bool);
  @override
  void updateCorrectScrollOffset() =>
      super.noSuchMethod(Invocation.method(#updateCorrectScrollOffset, []),
          returnValueForMissingStub: null);
  @override
  void updateScrollViewport() =>
      super.noSuchMethod(Invocation.method(#updateScrollViewport, []),
          returnValueForMissingStub: null);
  @override
  void resetScrollToZero() =>
      super.noSuchMethod(Invocation.method(#resetScrollToZero, []),
          returnValueForMissingStub: null);
  @override
  void setSelecting(bool? flag, {bool? notify = true}) => super.noSuchMethod(
      Invocation.method(#setSelecting, [flag], {#notify: notify}),
      returnValueForMissingStub: null);
  @override
  void setSelectingMode(_i3.PlutoGridSelectingMode? mode,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#setSelectingMode, [mode], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void setAllCurrentSelecting() =>
      super.noSuchMethod(Invocation.method(#setAllCurrentSelecting, []),
          returnValueForMissingStub: null);
  @override
  void setCurrentSelectingPosition(
          {_i3.PlutoGridCellPosition? cellPosition, bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#setCurrentSelectingPosition, [],
              {#cellPosition: cellPosition, #notify: notify}),
          returnValueForMissingStub: null);
  @override
  void setCurrentSelectingPositionByCellKey(_i4.Key? cellKey,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#setCurrentSelectingPositionByCellKey, [cellKey],
              {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void setCurrentSelectingPositionWithOffset(_i5.Offset? offset) =>
      super.noSuchMethod(
          Invocation.method(#setCurrentSelectingPositionWithOffset, [offset]),
          returnValueForMissingStub: null);
  @override
  void setCurrentSelectingRowsByRange(int? from, int? to,
          {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(
              #setCurrentSelectingRowsByRange, [from, to], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  void clearCurrentSelecting({bool? notify = true}) => super.noSuchMethod(
      Invocation.method(#clearCurrentSelecting, [], {#notify: notify}),
      returnValueForMissingStub: null);
  @override
  void toggleSelectingRow(int? rowIdx, {bool? notify = true}) =>
      super.noSuchMethod(
          Invocation.method(#toggleSelectingRow, [rowIdx], {#notify: notify}),
          returnValueForMissingStub: null);
  @override
  bool isSelectingInteraction() =>
      (super.noSuchMethod(Invocation.method(#isSelectingInteraction, []),
          returnValue: false) as bool);
  @override
  bool isSelectedRow(_i4.Key? rowKey) =>
      (super.noSuchMethod(Invocation.method(#isSelectedRow, [rowKey]),
          returnValue: false) as bool);
  @override
  bool isSelectedCell(
          _i3.PlutoCell? cell, _i3.PlutoColumn? column, int? rowIdx) =>
      (super.noSuchMethod(
          Invocation.method(#isSelectedCell, [cell, column, rowIdx]),
          returnValue: false) as bool);
  @override
  void handleAfterSelectingRow(_i3.PlutoCell? cell, dynamic value) => super
      .noSuchMethod(Invocation.method(#handleAfterSelectingRow, [cell, value]),
          returnValueForMissingStub: null);
  @override
  void updateVisibilityLayout({bool? notify = false}) => super.noSuchMethod(
      Invocation.method(#updateVisibilityLayout, [], {#notify: notify}),
      returnValueForMissingStub: null);
}

/// A class which mocks [PlutoGridEventManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlutoGridEventManager extends _i1.Mock
    implements _i3.PlutoGridEventManager {
  @override
  _i3.PlutoGridStateManager get stateManager =>
      (super.noSuchMethod(Invocation.getter(#stateManager),
              returnValue: _FakePlutoGridStateManager_14())
          as _i3.PlutoGridStateManager);
  @override
  _i2.PublishSubject<_i3.PlutoGridEvent> get subject =>
      (super.noSuchMethod(Invocation.getter(#subject),
              returnValue: _FakePublishSubject_0<_i3.PlutoGridEvent>())
          as _i2.PublishSubject<_i3.PlutoGridEvent>);
  @override
  _i6.StreamSubscription<dynamic> get subscription =>
      (super.noSuchMethod(Invocation.getter(#subscription),
              returnValue: _FakeStreamSubscription_15<dynamic>())
          as _i6.StreamSubscription<dynamic>);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void init() => super.noSuchMethod(Invocation.method(#init, []),
      returnValueForMissingStub: null);
  @override
  void addEvent(_i3.PlutoGridEvent? event) =>
      super.noSuchMethod(Invocation.method(#addEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i6.StreamSubscription<_i3.PlutoGridEvent> listener(
          void Function(_i3.PlutoGridEvent)? onData) =>
      (super.noSuchMethod(Invocation.method(#listener, [onData]),
              returnValue: _FakeStreamSubscription_15<_i3.PlutoGridEvent>())
          as _i6.StreamSubscription<_i3.PlutoGridEvent>);
}

/// A class which mocks [PlutoGridScrollController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlutoGridScrollController extends _i1.Mock
    implements _i3.PlutoGridScrollController {
  @override
  set vertical(_i3.LinkedScrollControllerGroup? _vertical) =>
      super.noSuchMethod(Invocation.setter(#vertical, _vertical),
          returnValueForMissingStub: null);
  @override
  set horizontal(_i3.LinkedScrollControllerGroup? _horizontal) =>
      super.noSuchMethod(Invocation.setter(#horizontal, _horizontal),
          returnValueForMissingStub: null);
  @override
  double get maxScrollHorizontal =>
      (super.noSuchMethod(Invocation.getter(#maxScrollHorizontal),
          returnValue: 0.0) as double);
  @override
  double get maxScrollVertical => (super
          .noSuchMethod(Invocation.getter(#maxScrollVertical), returnValue: 0.0)
      as double);
  @override
  double get verticalOffset =>
      (super.noSuchMethod(Invocation.getter(#verticalOffset), returnValue: 0.0)
          as double);
  @override
  double get horizontalOffset => (super
          .noSuchMethod(Invocation.getter(#horizontalOffset), returnValue: 0.0)
      as double);
  @override
  void setBodyRowsHorizontal(_i4.ScrollController? scrollController) =>
      super.noSuchMethod(
          Invocation.method(#setBodyRowsHorizontal, [scrollController]),
          returnValueForMissingStub: null);
  @override
  void setBodyRowsVertical(_i4.ScrollController? scrollController) => super
      .noSuchMethod(Invocation.method(#setBodyRowsVertical, [scrollController]),
          returnValueForMissingStub: null);
}

/// A class which mocks [LinkedScrollControllerGroup].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinkedScrollControllerGroup extends _i1.Mock
    implements _i3.LinkedScrollControllerGroup {
  @override
  double get offset =>
      (super.noSuchMethod(Invocation.getter(#offset), returnValue: 0.0)
          as double);
  @override
  _i4.ScrollController addAndGet() =>
      (super.noSuchMethod(Invocation.method(#addAndGet, []),
          returnValue: _FakeScrollController_16()) as _i4.ScrollController);
  @override
  void addOffsetChangedListener(_i5.VoidCallback? onChanged) => super
      .noSuchMethod(Invocation.method(#addOffsetChangedListener, [onChanged]),
          returnValueForMissingStub: null);
  @override
  void removeOffsetChangedListener(_i5.VoidCallback? listener) => super
      .noSuchMethod(Invocation.method(#removeOffsetChangedListener, [listener]),
          returnValueForMissingStub: null);
  @override
  _i6.Future<void> animateTo(double? offset,
          {_i4.Curve? curve, Duration? duration}) =>
      (super.noSuchMethod(
          Invocation.method(
              #animateTo, [offset], {#curve: curve, #duration: duration}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void jumpTo(double? value) =>
      super.noSuchMethod(Invocation.method(#jumpTo, [value]),
          returnValueForMissingStub: null);
  @override
  void resetScroll() => super.noSuchMethod(Invocation.method(#resetScroll, []),
      returnValueForMissingStub: null);
  @override
  void applyViewportDimension(double? value) =>
      super.noSuchMethod(Invocation.method(#applyViewportDimension, [value]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [ScrollController].
///
/// See the documentation for Mockito's code generation for more information.
class MockScrollController extends _i1.Mock implements _i4.ScrollController {
  @override
  bool get keepScrollOffset =>
      (super.noSuchMethod(Invocation.getter(#keepScrollOffset),
          returnValue: false) as bool);
  @override
  double get initialScrollOffset =>
      (super.noSuchMethod(Invocation.getter(#initialScrollOffset),
          returnValue: 0.0) as double);
  @override
  Iterable<_i4.ScrollPosition> get positions =>
      (super.noSuchMethod(Invocation.getter(#positions),
          returnValue: <_i4.ScrollPosition>[]) as Iterable<_i4.ScrollPosition>);
  @override
  bool get hasClients =>
      (super.noSuchMethod(Invocation.getter(#hasClients), returnValue: false)
          as bool);
  @override
  _i4.ScrollPosition get position =>
      (super.noSuchMethod(Invocation.getter(#position),
          returnValue: _FakeScrollPosition_17()) as _i4.ScrollPosition);
  @override
  double get offset =>
      (super.noSuchMethod(Invocation.getter(#offset), returnValue: 0.0)
          as double);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i6.Future<void> animateTo(double? offset,
          {Duration? duration, _i4.Curve? curve}) =>
      (super.noSuchMethod(
          Invocation.method(
              #animateTo, [offset], {#duration: duration, #curve: curve}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void jumpTo(double? value) =>
      super.noSuchMethod(Invocation.method(#jumpTo, [value]),
          returnValueForMissingStub: null);
  @override
  void attach(_i4.ScrollPosition? position) =>
      super.noSuchMethod(Invocation.method(#attach, [position]),
          returnValueForMissingStub: null);
  @override
  void detach(_i4.ScrollPosition? position) =>
      super.noSuchMethod(Invocation.method(#detach, [position]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  _i4.ScrollPosition createScrollPosition(_i4.ScrollPhysics? physics,
          _i4.ScrollContext? context, _i4.ScrollPosition? oldPosition) =>
      (super.noSuchMethod(
          Invocation.method(
              #createScrollPosition, [physics, context, oldPosition]),
          returnValue: _FakeScrollPosition_17()) as _i4.ScrollPosition);
  @override
  void debugFillDescription(List<String>? description) => super.noSuchMethod(
      Invocation.method(#debugFillDescription, [description]),
      returnValueForMissingStub: null);
  @override
  void addListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
