name: Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ['**/*.dart', '**/*.yml', '**/*.yaml', '**/*.gradle', '**/*.java']
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    steps:
      # Without this, there are no files in the directory.
      - uses: actions/checkout@v3
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.dartServer/.analysis-driver
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.yaml', 'analysis_options.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      # using flutter
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test --coverage
